### PR TITLE
Event categories

### PR DESCRIPTION
**Pull request by ldanilek**
* Events now color-coded by category/tag
* Events found by viewName instead of tag. Previously, the "All" category was more exclusive than the "Exhibitions" category.
* Fixed Bounds of events detail table view, so all events are visible
* Events now are displayed from their start date until their end date, not just on the start date.

### CODE REVIEW

**Comment by mrgoodboy** [comment]
good job on the color coding!
finding events by viewName will cause events of multiple tags to be in one category (try clicking community). Is this problem solvable? what is the rationale behind using viewName instead of tags?

**Comment by ldanilek** [comment]
From the JSON file pulled (either from tags or viewName), there is no way to tell what the category like "Arts" or "Community" is for each event. Each event has multiple tags (confusingly, in the JSON they are called "categories"), which sometimes overlaps between categories.

For example, check out the JSON pulled from http://calendar.yale.edu/feeds/feed/opa/json/2015-02-01/181days/viewName=Community . The first event has the tags ["class","community","family","meeting","other","recreation"]. So what Category should it be placed in? Classes and Workshops? Family Friendly? Sports and Recreation? Group Meetings? or Community? Working from just the event, it's impossible to tell, and this event shows up in each of these categories, so I just picked the color for the first tag it recognizes.

The reason I'm pulling with viewName is because that's how calendar.yale.edu sorts the events. When you pull from tags it for some reason gave more events for "Exhibitions" than "All." In addition some tags for categories were missing. Without changing to viewName the "Films" tags wouldn't have picked up "screening" events and the "Talks and Readings" tags wouldn't have picked up "lecture" events.

**Comment by mrgoodboy** [comment]
I see. in that case, if there are more tags, pick the color depending on what row the user selected, so that you don't have multiple tag colors in one calendar. if he/she selected "all", then you could pick the first tag. Is this reasonable ?

**Comment by ldanilek** [comment]
Color now depends on selected category; only collected from tags in "All" category. Also, the "Today" button selects the current date.

**Pull request merged**
